version: "3.2"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./../../:/home
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
